### PR TITLE
React16

### PR DESCRIPTION
**Pull request by will-moore**
Update React to latest version 16.2.

To test:
 - Filter & view Dataset in all 3 layouts
 - Filter & view Plate in all 3 layouts

### CODE REVIEW

**Comment by jburel** [comment]
excluding for now
parade is now deployed on web-dev-merge
--exclude

**Comment by jburel** [comment]
--exclude

**Comment by will-moore** [comment]
@chris-allan I seem to have this working now... Bit more testing...

**Comment by will-moore** [comment]
@jburel This seems to be working fine for me locally now. Probably worth removing the exclude now.

**Comment by joshmoore** [comment]
Removed, @will-moore

**Comment by jburel** [comment]
@will-moore I will re-enable the deployment of parade this evening on web-dev-merge

**Pull request merged**
