### PR TITLE
Map ann support

### PR DESCRIPTION
**Pull request by will-moore**
This allows filtering by Map Annotations.

NB: This PR is on top of @chris-allan python modules cleanup since I am editing one of the files that moved.

To test:
 - Choose ```Key_Value``` option from filter.
 - You can then choose a 'Key' to filter by. Default is the first key. Images are immediately filtered to only show those that have this Key.
 - Then can enter text to filter by Value.
 - Can combine filters as usual (see screenshot).

screen shot 2018-05-08 at 11 25 46

### CODE REVIEW

**Comment by pwalczysko** [comment]
After selecting a ``Key_Value`` in the menu (see screenshot) on the Dataset http://web-dev-merge.openmicroscopy.org/webclient/?show=dataset-18351 user-4

```
Traceback (most recent call last):

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/WEB-DEV-merge-deploy/OMERO.py/lib/python/omeroweb/decorators.py", line 488, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/omero_parade/views.py", line 127, in filter_script
    return module.get_script(request, filter_name, conn)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/omero_parade/annotation_filters/omero_filters.py", line 199, in get_script
    'default': keys[0]},

IndexError: list index out of range


<WSGIRequest
path:/omero_parade/filters/script/Key_Value/,
GET:<QueryDict: {u'project': [u'1204'], u'_': [u'1525874543527']}>,
POST:<QueryDict: {}>,
...
```

**Comment by pwalczysko** [comment]
>Default is the first key.

That is not what I see. On Dataset http://web-dev-merge.openmicroscopy.org/webclient/?show=dataset-19051 user-4, the first key is Temperature, but I get Pressure by default.
screen shot 2018-05-09 at 15 28 13


screen shot 2018-05-09 at 15 28 08

**Comment by pwalczysko** [comment]
Another error, when I try to combine filter of Pressure from the [comment](https://github.com/ome/omero-parade/pull/27#issuecomment-387758199)
 with ROI count

screen shot 2018-05-09 at 15 32 35

```
Traceback (most recent call last):

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/WEB-DEV-merge-deploy/OMERO.py/lib/python/omeroweb/decorators.py", line 488, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/omero_parade/views.py", line 181, in get_data
    'histogram': list(histogram)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/http/response.py", line 535, in __init__
    data = json.dumps(data, cls=encoder)

  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)

  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/serializers/json.py", line 115, in default
    return super(DjangoJSONEncoder, self).default(o)

  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: 117 is not JSON serializable


<WSGIRequest
path:/omero_parade/data/Uk9JX2NvdW50/,
GET:<QueryDict: {u'project': [u'3001'], u'_': [u'1525874543564']}>,
POST:<QueryDict: {}>,
...
```

**Comment by pwalczysko** [comment]
Interestingly, this error I get when I select for non-zero parameters. First, I selected for Key_Value, then for ``sizeT``. The dataset is http://web-dev-merge.openmicroscopy.org/webclient/?show=dataset-22351 the user is ``outreach`` on eel server. Note that all the images in the dataset have sizeT bigger than 2.

screen shot 2018-05-09 at 16 28 11


```
Traceback (most recent call last):

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/hudson/workspace/WEB-DEV-merge-deploy/OMERO.py/lib/python/omeroweb/decorators.py", line 488, in wrapped
    retval = f(request, *args, **kwargs)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/omero_parade/views.py", line 181, in get_data
    'histogram': list(histogram)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/http/response.py", line 535, in __init__
    data = json.dumps(data, cls=encoder)

  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)

  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)

  File "/home/hudson/virtualenv/lib/python2.7/site-packages/django/core/serializers/json.py", line 115, in default
    return super(DjangoJSONEncoder, self).default(o)

  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")

TypeError: 23 is not JSON serializable


<WSGIRequest
path:/omero_parade/data/c2l6ZVQ=/,
GET:<QueryDict: {u'project': [u'4451'], u'_': [u'1525877277050']}>,
POST:<QueryDict: {}>,
...
```

**Comment by pwalczysko** [comment]
I am in two minds here. Note, that none of the images in question has ``0microM`` as value to their Key ``mitomycin-A``. All have value ``10microM``. But my search for ``mitomycin-A``, ``0microM`` still delivers results, finding probably all ``...0microM``. This might need some thinking.

screen shot 2018-05-09 at 16 35 57

screen shot 2018-05-09 at 16 35 51

**Comment by pwalczysko** [comment]
Several problems:

  - https://github.com/ome/omero-parade/pull/27#issuecomment-387756855 (crash, maybe 0 items to filter for, and caused by the numpy version ?)
  - https://github.com/ome/omero-parade/pull/27#issuecomment-387758199 (ordering of Keys to select the default one to filter for)
  - https://github.com/ome/omero-parade/pull/27#issuecomment-387759712 (crash, hard to say why)
  - https://github.com/ome/omero-parade/pull/27#issuecomment-387778966 (crash, this time definitely the items to filter for were all there, so nothing what we encountered ever before seems to me)
  - https://github.com/ome/omero-parade/pull/27#issuecomment-387781159 (how to match Values ?)

**Comment by will-moore** [comment]
Commit 1dca069 fixes the first error from https://github.com/ome/omero-parade/pull/27#issuecomment-387756855

The ```TypeError: 117 is not JSON serializable``` errors are probably due to web-dev-merge's numpy version (not related to this PR) but these are from the ```Add table data...``` menu which you don't need to test for this PR.

The ordering of keys is simply alphabetic, not related to the ordering of keys in the individual map annotations (see screenshot above). Since we could have a ton of images, each with different keys in different orders, I think it could be hard to use their order in the filter menu.

When filtering by query text, I simply test to see if the query is found in the Value, so it certainly works better for text values than numerical values.

**Comment by pwalczysko** [comment]
>The ordering of keys is simply alphabetic, ...

Yes, well, it is an IT-alphabet. According to the screenshot, the capitalized Values are listed first in their entirety, then only come the non-capitalized ones starting with ``a``. That is hardly natural, and would lead many users astray (oh, my Value is not in this list, because it is ``k`` which is between ``M`` and  ``L``, and I do not see it there). But understood about the impossibility to find a better deafault.

**Comment by will-moore** [comment]
@pwalczysko Thanks - should have remembered that Python sorts uppercase differently from lowercase. 7d68fc8 should fix that.

**Comment by pwalczysko** [comment]
Last commit (alphabetical order) works as expected, and it helps.

**Comment by pwalczysko** [comment]
That fix https://github.com/ome/omero-parade/commit/1dca0695b1e817da04993278876637e3c5d42019 does not work entirely. It prevents crash, but there is some weird behaviour.
The images vanish, the css is not great. See screenshot.
screen shot 2018-05-11 at 11 45 37

**Comment by pwalczysko** [comment]
RFE: Would it be possible to offer ``negative hits filetering`` ?

I mean following workflow:

   - have some images, each of them has ``temperature`` and Value is ``37``, except just one or two images which have some other ``temperature``, a higher one (but I do not know what is exactly the value)
   - filetering for ``temperature`` and ``37`` works as expected, there is one or two images vanishing from display, but it is almost impossible to say which ones are those (sure, those are the ones which have a higher temperature, but I would like to inspect them and have no chance to target them)
   - I ended up entering in a row ``1``, ``2``, ``3``, ``4`` etc. in the Value. Finally, I found out that the "higher" temperature which I forgot was ``66``
   - could there be some option like ``temperature`` ``NOT`` ``37`` which would find that rogue image for me immediately ?

**Comment by chris-allan** [comment]
Will let these latest comments get addressed before merging.

**Comment by joshmoore** [comment]
> which would find that rogue image for me immediately ?

I like the idea of this (and it annoys me when other sites _don't_ provide this functionality) but this will likely have performance optimizations. Can I propose we should probably sit down next week and go over the types of queries that are likely to be needed and compare that with @mtbc's recent work to speed up map annotation queries?

**Comment by pwalczysko** [comment]
In summary

    - RFE about empty Key-Value pairs behaviour and about default key filetering https://github.com/ome/omero-parade/pull/27#issuecomment-388329688
    - RFE about ``negative hits`` filtering, which has some follow-ups on https://github.com/ome/omero-parade/pull/27#issuecomment-388332041 by @joshmoore

**Comment by mtbc** [comment]
Yes, my microservice should support queries like, "which images have temperature not 37?".

**Comment by will-moore** [comment]
That commit 538e924 adds a placeholder "Pick key..." which is shown initially and causes no filtering to occur. Only once you've chosen a key from the drop-down list does filtering happen.
In the case of NO map annotations are found, you can't pick a key, so NO filtering happens.

**Comment by will-moore** [comment]
@joshmoore Here we are loading All map annotations for a given list of images (so we can do the filtering in the browser). I don't know that @mtbc's recent work will have much impact here, but if there's a faster way to it then that would be great.

**Comment by pwalczysko** [comment]
>But I'd prefer not to add this within various filters.

That seems reasonable to me.

**Comment by joshmoore** [comment]
> so we can do the filtering in the browser

Remembering the discussion we had during the Tuesday presentation, however, I'd warn against adding significant new filtering methods without planning through how we're going to scale it up.

**Comment by joshmoore** [comment]
> Performance for large amount of data to handle is not covered in this PR (not its purpose)

Definitely agreed, but new features should be discussed to be technically possible at scale nevertheless.

**Comment by jburel** [comment]
Each time a filer is removed the key_value pairs are reloaded and UI regenerated
Example:

* Add ROI_count
* Add Key_value. wait for the UI to be built
* Remove ROI_count
*  The Key_value component will be rebuilt.

**Comment by will-moore** [comment]
That bug https://github.com/ome/omero-parade/pull/27#issuecomment-388823185 is not just for map_annotations, but will show up anytime you remove a filter (except for removing the *last* filter in the list).
This is because the ```key``` that tells React whether each filter is a new vv existing component is based on the name and Index.
```
<ParadeFilter
    key={fname + idx}
````
So, React will re-load filters if the index changes, which includes re-loading the filter and data from OMERO.
cc @chris-allan

**Comment by will-moore** [comment]
Kinda tricky to think how to fix that since you may have several filters with the same name e.g. ```Tag``` and a different Tag selected in each. If you remove one of them, we want React to remove just that one and not change the others. But it's hard to see how we can define a key for each filter based on the current state of each filter.

**Comment by will-moore** [comment]
Created https://github.com/ome/omero-parade/issues/38 from that last bug.

**Comment by jburel** [comment]
It is certainly more obvious now with the map annotation

**Pull request merged**
