### PR TITLE
Django 1.9

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/omero-web/pull/12

### CODE REVIEW

**Comment by will-moore** [comment]
Travis integrations test ERRORS due to:

```
    from omero.sys import ParametersI
ImportError: cannot import name 'ParametersI'
```
and
```
  File "/omero-parade/omero_parade/table_filters/omero_filters.py", line 18, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by joshmoore** [comment]
Would you propose adding it to the base image (omero-web-docker) or on a per app basis?

**Comment by will-moore** [comment]
We don't often use numpy on the web server (don't think any other apps need it), but maybe it doesn't do any harm having it in test-infra? I guess whichever is easier?

**Comment by joshmoore** [comment]
```diff
- 
+ Green!
```

**Comment by joshmoore** [comment]
JS error on https://py3-ci.openmicroscopy.org/web/webclient/:

```
Uncaught TypeError: omero_parade.omero_parade is not a function
    at jQuery.fn.init.load_plugin_content ((index):3024)
    at proxy (jquery-1.11.1.js:547)
    at update_plugin_content (ome.popup.js?_5.6.dev5:722)
    at HTMLBodyElement.<anonymous> (ome.popup.js?_5.6.dev5:759)
    at HTMLBodyElement.dispatch (jquery-1.11.1.js:4641)
    at HTMLBodyElement.elemData.handle (jquery-1.11.1.js:4309)
    at Object.trigger (jquery-1.11.1.js:4550)
    at HTMLBodyElement.<anonymous> (jquery-1.11.1.js:5260)
    at Function.each (jquery-1.11.1.js:383)
    at jQuery.fn.init.each (jquery-1.11.1.js:136)
```

**Comment by joshmoore** [comment]
@will-moore : parade is still failing on CI with the above.

**Comment by will-moore** [comment]
Now that we fail deployment if ```module.urls.py``` fails to import (https://github.com/ome/omero-web/pull/79 was merged yesterday) the latest-ci job is failing
because this PR is not merged.
https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-web/198/console

**Comment by joshmoore** [comment]
Understood. Happy to get this merged as the state of the python 3 migration. (Anyone want to propose a tag?)

Anything from functional testing can be rolled into new PRs.

**Comment by sbesson** [comment]
`0.2.dev1` ?

**Comment by joshmoore** [comment]
WFM. Is there any reason that parade can't be deployed by travis as well? cc: @jburel

**Comment by jburel** [comment]
not at all. We were catching up after the fact with app. I will sort it out

**Comment by jburel** [comment]
It should be deployed by travis when a tag is pushed
Everything is already set up

**Comment by joshmoore** [comment]
Sorry, must have been on an old master. I'll release then.

**Pull request merged**
