### PR TITLE
Update webpack-cli

### PR DESCRIPTION
**Pull request by jburel**
Update web-cli

This should fix the failure noticed in build
https://travis-ci.org/jburel/omero-plugins/builds/455462210

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: there are a few major versions bumps but I am not able to assess whether this would affect functionalities. Or are these build-time only dependencies?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [parade-merge#194](https://ci.openmicroscopy.org/job/parade-merge/194/). See the [console output](https://ci.openmicroscopy.org/job/parade-merge/194/consoleText) for more details.
Possible conflicts:
  - PR #39 chris-allan 'Expand all for Screens'
    - package-lock.json

--conflicts

**Comment by pwalczysko** [comment]
If you circumvent the bug https://github.com/ome/omero-parade/pull/53#issuecomment-439860940 by selecting the items in the dropdown in the order of appearance from top to bottom, then the graph does not work anyway.


screen shot 2018-11-19 at 11 28 19

**Comment by jburel** [comment]
I cannot reproduce the bug described by the first comment

**Comment by pwalczysko** [comment]
Cannot repeat the bug https://github.com/ome/omero-parade/pull/53#issuecomment-439860940 either. But the behaviour of the graph is not okay - I also seem to have some weird behavour on filtering by ``bounding box``

**Comment by will-moore** [comment]
@jburel - If this is good to merge (I think so) then please merge to avoid conflict with #55 (which needs the same fix to pass travis). Thanks

**Comment by jburel** [comment]
@will-moore: @pwalczysko reported a problem with the bounding box. I did not have time to check and I could not reproduce the issue. Will you have time to test?

**Comment by will-moore** [comment]
I don't see any bugs apart from the slightly strange behaviour caused by one image having a much larger Bounding box than all the other images. This makes a funny-looking plot and the filtering behaviour is wacky because the range of the slider is big compared to the lower values.

**Comment by jburel** [comment]
ok thanks @will-moore.
Merging so we can fix the build and move forward

**Pull request merged**
