### PR TITLE
try to use webgateway _bulk_file_annotations

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/openmicroscopy/openmicroscopy/pull/6054
Use the renamed ```_bulk_file_annotations()``` from webgateway (see PR above).
NB: Use ```try/except``` so we don't rely on OMERO 5.5.1 since users may want to upgrade OMERO.parade without having latest OMERO.

### CODE REVIEW

**Comment by will-moore** [comment]
Travis failed with getting docker running?
```
travis_fold:end:app-deps
Error response from daemon: Container 5dfdd3c1549cdb97e0ace0285291e7eeaf54eb56b0c206413ad764aedfa8e2db is not running
Stopping omeroparade_db_1  ... 
```

**Comment by joshmoore** [comment]
There have been a few issues with test-infra recently. I'll take a look.

**Comment by joshmoore** [comment]
Local run passed. I'm guessing resource starvation:
<details><summary>travis failure</summary>
<p>
```
2019-06-23 21:02:33,190 [omego.artifa] INFO  Unzipping OMERO.java-5.5.0-ice36-b121.zip
app-deps
Loaded plugins: fastestmirror, ovl
Examining /var/tmp/yum-root-QsQmxV/nodesource-release-el7-1.noarch.rpm: nodesource-release-el7-1.noarch
Marking /var/tmp/yum-root-QsQmxV/nodesource-release-el7-1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package nodesource-release.noarch 0:el7-1 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package              Arch     Version Repository                          Size
================================================================================
Installing:
 nodesource-release   noarch   el7-1   /nodesource-release-el7-1.noarch   3.1 k
Transaction Summary
================================================================================
Install  1 Package
Total size: 3.1 k
Installed size: 3.1 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : nodesource-release-el7-1.noarch                              1/1 
  Verifying  : nodesource-release-el7-1.noarch                              1/1 
Installed:
  nodesource-release.noarch 0:el7-1                                             
Complete!
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: centos4.zswap.net
 * epel: mirror.team-cymru.com
 * extras: centos4.zswap.net
 * updates: repo1.dal.innoscale.net
Resolving Dependencies
--> Running transaction check
---> Package npm.x86_64 1:3.10.10-1.6.16.0.1.el7 will be installed
--> Processing Dependency: nodejs = 1:6.16.0-1.el7 for package: 1:npm-3.10.10-1.6.16.0.1.el7.x86_64
--> Running transaction check
---> Package nodejs.x86_64 1:6.16.0-1.el7 will be installed
--> Processing Dependency: libuv >= 1:1.9.1 for package: 1:nodejs-6.16.0-1.el7.x86_64
--> Processing Dependency: libicudata.so.50()(64bit) for package: 1:nodejs-6.16.0-1.el7.x86_64
--> Processing Dependency: libicui18n.so.50()(64bit) for package: 1:nodejs-6.16.0-1.el7.x86_64
--> Processing Dependency: libicuuc.so.50()(64bit) for package: 1:nodejs-6.16.0-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: 1:nodejs-6.16.0-1.el7.x86_64
--> Running transaction check
---> Package libicu.x86_64 0:50.1.2-17.el7 will be installed
---> Package libuv.x86_64 1:1.29.1-1.el7 will be installed
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================
 Package       Arch          Version                          Repository   Size
================================================================================
Installing:
 npm           x86_64        1:3.10.10-1.6.16.0.1.el7         epel        2.5 M
Installing for dependencies:
 libicu        x86_64        50.1.2-17.el7                    base        6.9 M
 libuv         x86_64        1:1.29.1-1.el7                   epel        137 k
 nodejs        x86_64        1:6.16.0-1.el7                   epel        4.7 M
Transaction Summary
================================================================================
Install  1 Package (+3 Dependent packages)
Total download size: 14 M
Installed size: 51 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               18 MB/s |  14 MB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:libuv-1.29.1-1.el7.x86_64                                  1/4 
  Installing : libicu-50.1.2-17.el7.x86_64                                  2/4 
  Installing : 1:npm-3.10.10-1.6.16.0.1.el7.x86_64                          3/4 
  Installing : 1:nodejs-6.16.0-1.el7.x86_64                                 4/4 
  Verifying  : libicu-50.1.2-17.el7.x86_64                                  1/4 
  Verifying  : 1:libuv-1.29.1-1.el7.x86_64                                  2/4 
  Verifying  : 1:npm-3.10.10-1.6.16.0.1.el7.x86_64                          3/4 
  Verifying  : 1:nodejs-6.16.0-1.el7.x86_64                                 4/4 
Installed:
  npm.x86_64 1:3.10.10-1.6.16.0.1.el7                                           
Dependency Installed:
  libicu.x86_64 0:50.1.2-17.el7           libuv.x86_64 1:1.29.1-1.el7          
  nodejs.x86_64 1:6.16.0-1.el7           
Complete!
Error response from daemon: Container 5dfdd3c1549cdb97e0ace0285291e7eeaf54eb56b0c206413ad764aedfa8e2db is not running
Stopping omeroparade_db_1  ... 
Stopping omeroparade_web_1 ... 
oving omeroparade_db_1    ... 
Removing omeroparade_omero_1 ... 
Removing omeroparade_web_1   ... 
oving network omeroparade_default
The command ".omero/docker app" exited with 1.
```
Re-running with the hope that an early morning run has less contention. If OMERO is going to regular start failing in travis, we may have to rethink this strategy.

**Comment by joshmoore** [comment]
Interesting!

```
omero_1  | psql:omero-20190624-095938-201869.sql:9478: ERROR:  relation "i_logicalchannel_emissionwave" already exists
```

cc: @mtbc @jburel

**Comment by joshmoore** [comment]
Change looks fine. I don't assume a test is actually testing this, but travis is regardless green.

**Pull request merged**
