### PR TITLE
table.close() in try/finally blocks

### PR DESCRIPTION
**Pull request by will-moore**
Make sure we call ```table.close()``` whenever we open a table.

cc @joshmoore @chris-allan

### CODE REVIEW

**Comment by joshmoore** [comment]
```
./omero_parade/table_filters/data_providers.py:55:5: E722 do not use bare except'
./omero_parade/table_filters/data_providers.py:151:80: E501 line too long (82 > 79 characters)
```

Once this is fixed, I could see releasing a 0.1.3

**Comment by will-moore** [comment]
@joshmoore flake8 fixed (and I used ```finally``` instead of ```except```, which I should have done first time).

**Comment by will-moore** [comment]
If we're releasing, it would be great to have https://github.com/ome/omero-parade/pull/55 merged and included since we've got several reports of that bug (internally and externally).

**Comment by joshmoore** [comment]
Merging for 0.1.3

**Pull request merged**
